output-reports:
  active: true
  exclude:
    - 'TxtOutputReport'
    - 'XmlOutputReport'
    - 'HtmlOutputReport'
    - 'MdOutputReport'

comments:
  active: false

complexity:
  active: true
  ComplexInterface:
    active: true
  LargeClass:
    active: true
    threshold: 400
  LongMethod:
    active: true
    threshold: 30
    excludes: &testDirsAndCompose
      - '**/test/**'
      - '**/androidTest/**'
      - '**/screen/**'
      - '**/view/**'
  LongParameterList:
    active: true
    excludes: *testDirsAndCompose
  MethodOverloading:
    active: false
  NamedArguments:
    active: true
    threshold: 2
  StringLiteralDuplication:
    active: true
    excludes: &testDirs
      - '**/test/**'
      - '**/androidTest/**'
  TooManyFunctions:
    active: true
    excludes: *testDirs

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  SuspendFunWithCoroutineScopeReceiver:
    active: true

exceptions:
  active: true
  InstanceOfCheckForException:
    active: true
    excludes: *testDirs
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
    excludes: *testDirs
  TooGenericExceptionCaught:
    active: false

naming:
  active: true
  BooleanPropertyNaming:
    active: true
  FunctionMaxLength:
    active: true
    excludes: *testDirs
    maximumFunctionNameLength: 30
  FunctionNaming:
    active: false
  NonBooleanPropertyPrefixedWithIs:
    active: true
  PackageNaming:
    active: true
    packagePattern: '[a-z]+(\.[a-z]*)*'
  VariableMaxLength:
    active: true
    maximumVariableNameLength: 32

performance:
  active: true
  CouldBeSequence:
    active: true
    threshold: 2
  ForEachOnRange:
    active: true
    excludes: *testDirs
  SpreadOperator:
    active: true
    excludes: *testDirs

potential-bugs:
  active: true
  CastToNullableType:
    active: true
  ImplicitUnitReturnType:
    active: true
  NullCheckOnMutableProperty:
    active: true
  NullableToStringCall:
    active: true
  UnsafeCallOnNullableType:
    active: true
    excludes: *testDirs

style:
  active: true
  NewLineAtEndOfFile:
    active: false
