name: Coverage

on:
  push:
    branches:
      - master
    paths:
      - "**.kt"

jobs:
  report:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - run: |
          echo "${{ secrets.DEPLOY_SIGNING_KEY }}" | base64 --decode > keystore.jks
          echo "${{ secrets.DEPLOY_SIGNING_PROPERTIES }}" | base64 --decode > keystore.properties
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json
          echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" | base64 --decode > service-account.json
          echo "MM_BASIC_USER=${{ secrets.BASIC_USER }}" >> secrets.properties
          echo "MM_BASIC_PASS=${{ secrets.BASIC_PASS }}" >> secrets.properties
          echo "MM_CAPTCHA=${{ secrets.CAPTCHA }}" >> secrets.properties

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Run detekt
        run: ./gradlew rootCoverage

      - name: Run Codacy reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_TOKEN }}
          coverage-reports: build/reports/jacoco.xml